v6 readme update
FortAwesome/wordpress-fontawesome pull request #153
Opened 2021-12-10 17:11 UTC by ej2

2021-12-10 18:17 UTC, mlwilkerson requested changes

2021-12-10 18:17 UTC, mlwilkerson commented on README.md
> +In that case, then you might prefer to do a [custom installation](https://fontawesome.com/v6.0/docs/web/use-with/wordpress) _instead_ of using this plugin package.
The link for custom/manual/advanced/non-plugin installation is intentionally deeper in the doc hierarchy than the top-level "use with WordPress" link. The original link here was intended to deep-link directly to that manual installation guide, saving the expert user from several drill-down clicks. But the updated link one goes to the top-level docs, from which they'd have to drill down.

When I go to that new link:
`https://fontawesome.com/v6.0/docs/web/use-with/wordpress`

And then click "Manual Installation (Advanced)" from its table of contents, it jumps me down to here on that same page:
`https://fontawesome.com/v6.0/docs/web/use-with/wordpress#manual-installation-advanced`

And that shows a section with another link into the actual advanced docs:
`https://fontawesome.com/v5.15/how-to-use/customizing-wordpress/intro/getting-started`

Notice the `v5.15` in that URL. I just attempted to change that to `v6.0` and it results in a 404.

So apparently, we don't yet have those manual installation docs available under a `v6.0` URL. In the meantime, I think that final URL is what this README should be pointing to.

2022-01-26 19:27 UTC, talbs commented
@mlwilkerson and @ej2, I pushed a few commits based on some updates to docs and URLs that have shaken out this split. I think https://github.com/FortAwesome/wordpress-fontawesome/pull/153/commits/84f052bf91d540d4a10d5da28f0829f77fab07b2 should resolve your earlier comment, @mlwilkerson.

Let me know if any of these changes don't make sense.

2022-01-26 22:54 UTC, mlwilkerson commented
Ok, great. Thanks @talbs. Looks good to me. Since that new link isn't live on the site yet, I'll wait to merge these changes until it is.

2022-01-26 22:54 UTC, mlwilkerson approved these changes

2022-02-10 21:38 UTC, merged